# Generated by Django 2.1.2 on 2018-11-22 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShareUserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.FloatField(verbose_name='最终')),
                ('price', models.FloatField(verbose_name='可提现佣金')),
                ('cash_price', models.FloatField(verbose_name='成功提现佣金')),
                ('total_cash', models.FloatField(verbose_name='分销佣金')),
                ('team_count', models.IntegerField(verbose_name='我的团队人数')),
                ('order_money', models.FloatField(verbose_name='分销订单')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='share.ShareUser', verbose_name='用户分销详细资料')),
            ],
        ),
        migrations.AlterField(
            model_name='sharegoods',
            name='goods',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wx_league.Goods', verbose_name='分销商品'),
        ),
    ]
