# Generated by Django 2.1.2 on 2018-11-22 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0004_auto_20181122_1442'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shareuserprofile',
            name='unpay',
        ),
        migrations.AddField(
            model_name='shareuserprofile',
            name='un_pay',
            field=models.FloatField(default=0, verbose_name='分销订单'),
        ),
        migrations.AlterField(
            model_name='sharegoods',
            name='goods',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wx_league.Goods', verbose_name='分销商品'),
        ),
    ]
