# Generated by Django 2.1.2 on 2018-11-24 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0006_auto_20181122_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cash',
            name='status',
            field=models.SmallIntegerField(choices=[(0, '待审核'), (1, '待打款'), (2, '已打款'), (3, '无效'), (4, '取消')], default=0, verbose_name='提现状态'),
        ),
        migrations.AlterField(
            model_name='sharegoods',
            name='goods',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wx_league.Goods', verbose_name='分销商品'),
        ),
    ]
