# Generated by Django 2.1.2 on 2018-11-26 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0012_auto_20181126_1107'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shareorder',
            name='coupons',
        ),
        migrations.RemoveField(
            model_name='shareorder',
            name='user',
        ),
        migrations.RemoveField(
            model_name='shareordergoods',
            name='goods',
        ),
        migrations.AddField(
            model_name='sharegoods',
            name='cash_scheme',
            field=models.SmallIntegerField(choices=[(0, '[0.07, 0.02, 0.01]'), (1, '[0.035, 0.010, 0.05]'), (2, '[0.07, 0.02, 0.01]'), (3, '[0.12, 0.02, 0.01]')], default=0),
        ),
        migrations.AddField(
            model_name='shareordergoods',
            name='sharegoods',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='share.ShareGoods', verbose_name='分销商品'),
        ),
        migrations.AlterField(
            model_name='sharegoods',
            name='goods',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wx_league.Goods', verbose_name='分销商品'),
        ),
        migrations.AlterField(
            model_name='sharegoods',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wx_league.DriverSchool', verbose_name='分销商'),
        ),
        migrations.AlterField(
            model_name='shareordergoods',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wx_league.Order', verbose_name='订单'),
        ),
        migrations.DeleteModel(
            name='ShareOrder',
        ),
    ]
