# Generated by Django 2.1.3 on 2018-11-06 01:38

import base.models.user
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('username', models.CharField(help_text='Required. 30 characters or fewer. Letters, digits and ./+/-/_ only.', max_length=30, unique=True, validators=[django.core.validators.RegexValidator('^[\\w.+-]+$', 'Enter a valid username jebal.', 'invalid')], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=30, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('image', models.ImageField(blank=True, default='Images/None/No-img.jpg', null=True, upload_to='Images/')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'swappable': 'AUTH_USER_MODEL',
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
        ),
        migrations.CreateModel(
            name='Icon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='图标名称')),
                ('display_pic', models.ImageField(upload_to=base.models.user.filepath, verbose_name='icon 对应')),
                ('date_add', models.DateTimeField(auto_now_add=True, null=True, verbose_name='上传时间')),
            ],
            options={
                'verbose_name': '图标',
                'db_table': 'Icon',
                'verbose_name_plural': '图标',
            },
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province_id', models.IntegerField(default=0, verbose_name='省')),
                ('city_id', models.IntegerField(default=0, verbose_name='城市')),
                ('district_id', models.IntegerField(default=0, verbose_name='区')),
                ('name', models.CharField(max_length=30, verbose_name='店铺名称')),
                ('address', models.CharField(blank=True, max_length=100, null=True, verbose_name='地址')),
                ('phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='联系电话')),
                ('introduce', models.TextField(verbose_name='介绍')),
                ('characteristic', models.TextField(verbose_name='特色')),
                ('sort', models.IntegerField(verbose_name='排序')),
                ('activity', models.CharField(max_length=255, verbose_name='打折优惠信息')),
                ('latitude', models.FloatField(verbose_name='纬度')),
                ('longitude', models.FloatField(verbose_name='经度')),
                ('number_good_reputation', models.IntegerField(verbose_name='好评数')),
                ('number_order', models.IntegerField(verbose_name='订单数')),
                ('pic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.Icon', verbose_name='店铺商标')),
            ],
            options={
                'verbose_name': '商店',
                'db_table': 'Shop',
                'verbose_name_plural': '商店',
            },
        ),
        migrations.CreateModel(
            name='ViewedProfileTracking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visited_time', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='who_visit_profile', to=settings.AUTH_USER_MODEL)),
                ('visited_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visited_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
