# Generated by Django 2.1.3 on 2018-11-14 03:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('emall', '0006_auto_20181112_2147'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bargain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('times', models.IntegerField(default=0, verbose_name='砍价次数')),
                ('price', models.FloatField(verbose_name='砍价当前价格')),
                ('min_price', models.FloatField(verbose_name='砍价最低价格')),
                ('calculate_method', models.SmallIntegerField(choices=[(0, 'line'), (1, 'log')], verbose_name='砍价计算模式')),
                ('expected_price', models.FloatField(verbose_name='期望砍价价格')),
                ('expected_times', models.FloatField(verbose_name='期望砍价次数')),
                ('date_start', models.DateTimeField(auto_now_add=True, verbose_name='活动开始时间')),
                ('date_end', models.DateTimeField(verbose_name='活动结束时间')),
            ],
            options={
                'verbose_name_plural': '砍价',
                'verbose_name': '砍价',
                'db_table': 'Bargain',
            },
        ),
        migrations.CreateModel(
            name='BargainFriend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField(verbose_name='砍价次序')),
                ('date_add', models.DateTimeField(auto_now_add=True, verbose_name='砍价时间')),
                ('bargain_friend', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='参与砍价好友')),
            ],
            options={
                'verbose_name_plural': '帮忙砍价的好友',
                'verbose_name': '帮忙砍价的好友',
                'db_table': 'BargainFriend',
            },
        ),
        migrations.CreateModel(
            name='BargainUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bargain_date', models.DateTimeField(auto_now_add=True, verbose_name='砍价发起时间')),
                ('bargain', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='emall.Bargain', verbose_name='砍价活动')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='砍价用户')),
            ],
            options={
                'verbose_name_plural': '砍价用户记录',
                'verbose_name': '砍价用户记录',
                'db_table': 'BargainUser',
            },
        ),
        migrations.CreateModel(
            name='Coupons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='优惠券名称')),
                ('money_min', models.FloatField(verbose_name='优惠券金额')),
                ('money_hreshold', models.FloatField(verbose_name='满 减 最低额度')),
                ('date_end_type', models.SmallIntegerField(choices=[(0, '截止某日前有效'), (1, '领取后有效时间倒计')], verbose_name='优惠券有效期类型')),
                ('date_end_days', models.DateTimeField(default=django.utils.timezone.now, verbose_name='优惠券截止时间')),
                ('is_active', models.BooleanField(verbose_name='优惠券是否有效')),
                ('date_add', models.DateTimeField(default=django.utils.timezone.now, verbose_name='优惠券添加的时间')),
                ('coupons_type', models.SmallIntegerField(default=0, verbose_name='优惠券类型1.通用型,2.分类专用型,3.商品专用型,4.店铺专用型')),
            ],
            options={
                'verbose_name_plural': '优惠券',
                'verbose_name': '优惠券',
                'db_table': 'Coupons',
            },
        ),
        migrations.CreateModel(
            name='CouponsUsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_add', models.DateTimeField(default=django.utils.timezone.now, verbose_name='优惠券添加的时间')),
                ('date_end', models.DateTimeField(default=django.utils.timezone.now, verbose_name='优惠券截止时间')),
                ('coupons', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='emall.Coupons', verbose_name='优惠券id')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='用户id')),
            ],
            options={
                'verbose_name_plural': '用户领取的优惠券',
                'verbose_name': '用户领取的优惠券',
                'db_table': 'Coupons_users',
            },
        ),
        migrations.AlterModelManagers(
            name='goods',
            managers=[
                ('sorted_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RemoveField(
            model_name='order',
            name='logistics_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='logistics_price',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shipper_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='tracking_number',
        ),
        migrations.AddField(
            model_name='coupons',
            name='goods',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='emall.Goods', verbose_name='商品id'),
        ),
        migrations.AddField(
            model_name='bargainfriend',
            name='bargain_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='emall.BargainUser', verbose_name='砍价发起用户'),
        ),
        migrations.AddField(
            model_name='bargain',
            name='goods',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='emall.Goods', verbose_name='货物'),
        ),
    ]
