# Generated by Django 2.1.3 on 2018-11-14 13:41

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('emall', '0007_auto_20181114_1150'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CouponsUsers',
            new_name='CouponsUser',
        ),
    ]
