# Generated by Django 2.1.3 on 2018-11-06 01:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='名称')),
                ('key', models.IntegerField(verbose_name='编号')),
                ('is_use', models.BooleanField(default=True, verbose_name='是否启用')),
                ('sort', models.IntegerField(verbose_name='排序')),
                ('pid', models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='scheme.Category', verbose_name='上级分类')),
            ],
            options={
                'verbose_name': '方案分类',
                'db_table': 'FangAnCategory',
                'verbose_name_plural': '方案分类',
            },
        ),
        migrations.CreateModel(
            name='Scheme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='方案标题')),
                ('content', models.TextField(verbose_name='方案内容')),
                ('category_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='scheme.Category', verbose_name='方案分类')),
                ('editors', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='编辑者')),
                ('index_pic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.Icon', verbose_name='方案封面图')),
            ],
            options={
                'verbose_name': '方案',
                'db_table': 'Scheme',
                'verbose_name_plural': '方案',
            },
        ),
    ]
