# Generated by Django 2.1.3 on 2018-11-12 01:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('scheme', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheme',
            name='date_create',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2018, 11, 12, 1, 27, 11, 925985, tzinfo=utc), verbose_name='创建日期'),
            preserve_default=False,
        ),
    ]
