# Generated by Django 2.1.3 on 2018-11-12 02:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheme', '0002_scheme_date_create'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='pid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='scheme.Category', verbose_name='上级分类'),
        ),
    ]
