# Generated by Django 2.1.3 on 2018-11-12 06:35

import base.models.user
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20181108_0920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='icon',
            name='display_pic',
            field=base.models.user.ImgField(upload_to=base.models.user.filepath, verbose_name='icon 对应'),
        ),
    ]
