# Generated by Django 2.1.3 on 2018-11-12 06:47

import base.models.user
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20181112_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='icon',
            name='display_pic',
            field=models.ImageField(upload_to=base.models.user.filepath, verbose_name='icon 对应'),
        ),
    ]
