# Generated by Django 2.1 on 2018-08-14 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wx_league', '0026_auto_20180814_0508'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goods',
            options={'verbose_name': '商品', 'verbose_name_plural': '商品'},
        ),
    ]
