# Generated by Django 2.1 on 2018-08-14 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wx_league', '0027_auto_20180814_0511'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='goods',
            table=None,
        ),
    ]
