# Generated by Django 2.1.3 on 2018-11-06 01:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='名称')),
                ('eng_name', models.CharField(max_length=100, verbose_name='名称(英文)')),
                ('category_type', models.CharField(max_length=30, verbose_name='类型')),
                ('key', models.IntegerField(verbose_name='编号')),
                ('level', models.SmallIntegerField(verbose_name='分类级别')),
                ('is_use', models.BooleanField(default=True, verbose_name='是否启用')),
                ('sort', models.IntegerField(verbose_name='排序')),
                ('icon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.Icon', verbose_name='图标')),
                ('pid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='emall.Category', verbose_name='上级分类')),
            ],
            options={
                'verbose_name': '商品分类',
                'db_table': 'Category',
                'verbose_name_plural': '商品分类',
            },
        ),
        migrations.CreateModel(
            name='DeliverWizard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_number', models.CharField(max_length=200, verbose_name='运单号')),
                ('status', models.CharField(max_length=20, verbose_name='状态')),
            ],
            options={
                'verbose_name': '发货信息',
                'db_table': 'DeliverWizard',
                'verbose_name_plural': '发货信息',
            },
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('characteristic', models.CharField(default='', max_length=100, verbose_name='描述')),
                ('date_add', models.DateTimeField(auto_now_add=True, verbose_name='上架时间')),
                ('date_start', models.DateTimeField(auto_now_add=True, verbose_name='上架时间')),
                ('date_update', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('logistics_id', models.IntegerField(default=0, verbose_name='物流id')),
                ('min_score', models.SmallIntegerField(default=0, verbose_name='最小评分')),
                ('name', models.CharField(max_length=60, verbose_name='名称')),
                ('number_fav', models.IntegerField(default=0, verbose_name='收藏人数')),
                ('number_good_reputation', models.IntegerField(default=0, verbose_name='好评数量')),
                ('number_orders', models.IntegerField(default=0, verbose_name='已售数量')),
                ('original_price', models.FloatField(verbose_name='原价')),
                ('paixu', models.IntegerField(default=0)),
                ('pingtuan', models.BooleanField(default=False, verbose_name='拼团')),
                ('recommend_status', models.SmallIntegerField(default=0, verbose_name='推荐状态')),
                ('status', models.SmallIntegerField(default=0, verbose_name='商品状态')),
                ('stores', models.IntegerField(verbose_name='库存')),
                ('video_id', models.IntegerField(default=0)),
                ('views', models.IntegerField(default=0)),
                ('weight', models.FloatField(default=0.0)),
                ('category_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='emall.Category')),
                ('pic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.Icon', verbose_name='商品图片连接')),
                ('shop_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Shop', verbose_name='商店id')),
            ],
            options={
                'verbose_name': '商品',
                'verbose_name_plural': '商品',
            },
        ),
        migrations.CreateModel(
            name='Logistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='名称')),
                ('by_self', models.BooleanField(default=False, verbose_name='商家配送')),
                ('free', models.BooleanField(default=False, verbose_name='是否包邮')),
                ('valuation_type', models.SmallIntegerField(default=0, verbose_name='计价方式')),
            ],
            options={
                'verbose_name': '物流信息',
                'db_table': 'Logistics',
                'verbose_name_plural': '物流信息',
            },
        ),
        migrations.CreateModel(
            name='ModifyPriceWizard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.FloatField(verbose_name='金额')),
            ],
            options={
                'verbose_name': '修改价格',
                'db_table': 'ModifyPriceWizard',
                'verbose_name_plural': '修改价格',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_goods', models.IntegerField(default=0, verbose_name='商品数量')),
                ('goods_price', models.FloatField(default=0, verbose_name='商品总金额')),
                ('coupons_id', models.IntegerField(default=0, verbose_name='使用的优惠券id')),
                ('logistics_price', models.FloatField(default=0, verbose_name='物流费用')),
                ('total', models.FloatField(default=0, verbose_name='实际支付')),
                ('status', models.SmallIntegerField(choices=[(0, '待付款'), (1, '待发货'), (2, '待收货'), (3, '待评价'), (4, '已完成'), (5, '已删除')], default=0, verbose_name='状态')),
                ('remark', models.CharField(blank=True, max_length=100, verbose_name='备注')),
                ('linkman', models.CharField(blank=True, max_length=100, verbose_name='联系人')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='手机号码')),
                ('province_id', models.SmallIntegerField(default=0, verbose_name='省')),
                ('city_id', models.SmallIntegerField(default=0, verbose_name='市')),
                ('district_id', models.SmallIntegerField(default=0, verbose_name='区')),
                ('address', models.CharField(blank=True, max_length=100, verbose_name='详细地址')),
                ('postcode', models.CharField(blank=True, max_length=20, verbose_name='邮政编码')),
                ('tracking_number', models.CharField(blank=True, max_length=200, verbose_name='运单号')),
                ('traces', models.TextField(blank=True, verbose_name='物流信息')),
                ('date_add', models.DateTimeField(default=django.utils.timezone.now, verbose_name='下单时间')),
                ('logistics_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='emall.Logistics', verbose_name='物流id')),
            ],
            options={
                'verbose_name': '订单',
                'db_table': 'Order',
                'verbose_name_plural': '订单',
            },
        ),
        migrations.CreateModel(
            name='OrderGoods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField(default=0, verbose_name='订单')),
                ('goods_id', models.IntegerField(default=0, verbose_name='商品id')),
                ('name', models.CharField(blank=True, max_length=50, verbose_name='商品名称')),
                ('property_str', models.CharField(blank=True, max_length=200, verbose_name='商品规格')),
                ('price', models.FloatField(default=0, verbose_name='单价')),
                ('amount', models.IntegerField(default=0, verbose_name='商品数量')),
                ('total', models.FloatField(default=0, verbose_name='总价')),
                ('display_pic', models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='base.Icon', verbose_name='图片')),
            ],
            options={
                'verbose_name': '订单商品',
                'db_table': 'OrderGoods',
                'verbose_name_plural': '订单商品',
            },
        ),
        migrations.CreateModel(
            name='Shipper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='名称')),
                ('code', models.CharField(max_length=100, verbose_name='编码')),
            ],
            options={
                'verbose_name': '承运商',
                'db_table': 'Shipper',
                'verbose_name_plural': '承运商',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='shipper_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='emall.Shipper', verbose_name='快递承运商'),
        ),
        migrations.AddField(
            model_name='order',
            name='wechat_user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='微信用户'),
        ),
        migrations.AddField(
            model_name='modifypricewizard',
            name='order_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emall.Order', verbose_name='订单'),
        ),
        migrations.AddField(
            model_name='deliverwizard',
            name='order_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emall.Order', verbose_name='订单'),
        ),
        migrations.AddField(
            model_name='deliverwizard',
            name='shipper_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emall.Shipper', verbose_name='快递承运商'),
        ),
    ]
