# Generated by Django 2.1.3 on 2018-11-11 14:48

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('emall', '0002_goodsreputation_preferential'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='preferential',
            managers=[
                ('sorted_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
