# Generated by Django 2.1.3 on 2018-11-11 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emall', '0003_auto_20181111_2248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preferential',
            name='preferential_type',
            field=models.SmallIntegerField(choices=[(0, 'preferentail'), (1, 'inventory'), (2, 'offer')], max_length=50),
        ),
    ]
