# Generated by Django 2.1.3 on 2018-11-17 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emall', '0008_auto_20181114_2141'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='wechat_user_id',
            new_name='user',
        ),
    ]
