# Generated by Django 2.1 on 2018-08-09 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wx_league', '0005_auto_20180809_2315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wechatuser',
            name='cookie',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='用户认证标识'),
        ),
    ]
