# Generated by Django 2.1 on 2018-08-10 02:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('wx_league', '0006_auto_20180809_2316'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupons',
            name='dateEndDays',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='优惠券截止时间'),
        ),
        migrations.AddField(
            model_name='coupons',
            name='date_add',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='优惠券添加的时间0'),
        ),
    ]
