# Generated by Django 2.1 on 2018-08-10 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wx_league', '0009_auto_20180810_0415'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupons',
            name='coupons_type',
            field=models.SmallIntegerField(default=0, verbose_name='优惠券类型1.通用型,2.分类专用型,3.商品专用型,4.店铺专用型'),
        ),
    ]
