# Generated by Django 2.1 on 2018-08-11 23:48

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('wx_league', '0010_coupons_coupons_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupons_users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(verbose_name='用户id')),
                ('date_add', models.DateTimeField(default=django.utils.timezone.now, verbose_name='优惠券添加的时间')),
                ('dateEndDays', models.DateTimeField(default=django.utils.timezone.now, verbose_name='优惠券截止时间')),
            ],
        ),
        migrations.RemoveField(
            model_name='coupons',
            name='date',
        ),
        migrations.AddField(
            model_name='coupons_users',
            name='coupons_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wx_league.Coupons', verbose_name='优惠券id'),
        ),
    ]
