# Generated by Django 2.1 on 2018-08-12 03:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('wx_league', '0013_auto_20180812_0244'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='dateAdd',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='下单时间'),
        ),
    ]
