# Generated by Django 2.1 on 2018-08-12 06:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wx_league', '0015_auto_20180812_0448'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_num',
        ),
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.CharField(blank=True, max_length=100, verbose_name='详细地址'),
        ),
        migrations.AlterField(
            model_name='order',
            name='city_id',
            field=models.SmallIntegerField(blank=True, verbose_name='市'),
        ),
        migrations.AlterField(
            model_name='order',
            name='district_id',
            field=models.SmallIntegerField(blank=True, verbose_name='区'),
        ),
        migrations.AlterField(
            model_name='order',
            name='linkman',
            field=models.CharField(blank=True, max_length=100, verbose_name='联系人'),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.CharField(blank=True, max_length=50, verbose_name='手机号码'),
        ),
        migrations.AlterField(
            model_name='order',
            name='postcode',
            field=models.CharField(blank=True, max_length=20, verbose_name='邮政编码'),
        ),
        migrations.AlterField(
            model_name='order',
            name='province_id',
            field=models.SmallIntegerField(blank=True, verbose_name='省'),
        ),
        migrations.AlterField(
            model_name='order',
            name='remark',
            field=models.CharField(blank=True, max_length=100, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipper_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='wx_league.Shipper', verbose_name='快递承运商'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.SmallIntegerField(choices=[(0, '待付款'), (1, '待发货'), (2, '待收货'), (3, '待评价'), (4, '已完成'), (5, '已删除')], default=0, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='order',
            name='traces',
            field=models.TextField(blank=True, verbose_name='物流信息'),
        ),
        migrations.AlterField(
            model_name='order',
            name='tracking_number',
            field=models.CharField(blank=True, max_length=200, verbose_name='运单号'),
        ),
    ]
