# Generated by Django 2.1 on 2018-08-12 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wx_league', '0016_auto_20180812_0611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='number_goods',
            field=models.IntegerField(blank=True, verbose_name='商品数量'),
        ),
    ]
