# Generated by Django 2.1 on 2018-08-12 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wx_league', '0017_auto_20180812_0614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='city_id',
            field=models.SmallIntegerField(default=0, verbose_name='市'),
        ),
        migrations.AlterField(
            model_name='order',
            name='district_id',
            field=models.SmallIntegerField(default=0, verbose_name='区'),
        ),
        migrations.AlterField(
            model_name='order',
            name='province_id',
            field=models.SmallIntegerField(default=0, verbose_name='省'),
        ),
        migrations.AlterField(
            model_name='ordergoods',
            name='goods_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='wx_league.goods', verbose_name='商品id'),
        ),
    ]
