# Generated by Django 2.1 on 2018-08-12 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wx_league', '0019_auto_20180812_0632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordergoods',
            name='amount',
            field=models.IntegerField(default=0, verbose_name='商品数量'),
        ),
        migrations.AlterField(
            model_name='ordergoods',
            name='display_pic',
            field=models.ImageField(blank=True, upload_to='', verbose_name='图片'),
        ),
        migrations.AlterField(
            model_name='ordergoods',
            name='name',
            field=models.CharField(blank=True, max_length=50, verbose_name='商品名称'),
        ),
        migrations.AlterField(
            model_name='ordergoods',
            name='price',
            field=models.FloatField(default=0, verbose_name='单价'),
        ),
        migrations.AlterField(
            model_name='ordergoods',
            name='property_str',
            field=models.CharField(blank=True, max_length=200, verbose_name='商品规格'),
        ),
        migrations.AlterField(
            model_name='ordergoods',
            name='total',
            field=models.FloatField(default=0, verbose_name='总价'),
        ),
    ]
