# Generated by Django 2.1 on 2018-08-12 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wx_league', '0022_auto_20180812_0657'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordergoods',
            name='pic',
        ),
    ]
