# Generated by Django 2.1 on 2018-08-12 08:56

from django.db import migrations, models
import wx_league.models


class Migration(migrations.Migration):

    dependencies = [
        ('wx_league', '0024_auto_20180812_0845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='icon',
            name='display_pic',
            field=models.ImageField(upload_to=wx_league.models.filepath, verbose_name='icon 对应'),
        ),
    ]
