# Generated by Django 2.1 on 2018-08-15 14:41

from django.db import migrations, models
import django.db.models.deletion
import wx_league.models


class Migration(migrations.Migration):

    dependencies = [
        ('wx_league', '0025_auto_20180812_0856'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attachment',
            options={'verbose_name': '图片', 'verbose_name_plural': '图片'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': '商品分类', 'verbose_name_plural': '商品分类'},
        ),
        migrations.AlterModelOptions(
            name='coupons',
            options={'verbose_name': '优惠券', 'verbose_name_plural': '优惠券'},
        ),
        migrations.AlterModelOptions(
            name='coupons_users',
            options={'verbose_name': '用户领取的优惠券', 'verbose_name_plural': '用户领取的优惠券'},
        ),
        migrations.AlterModelOptions(
            name='driverschool',
            options={'verbose_name': '驾校', 'verbose_name_plural': '驾校'},
        ),
        migrations.AlterModelOptions(
            name='goods',
            options={'verbose_name': '商品', 'verbose_name_plural': '商品'},
        ),
        migrations.AlterModelOptions(
            name='icon',
            options={'verbose_name': '图标', 'verbose_name_plural': '图标'},
        ),
        migrations.AlterModelOptions(
            name='modifypricewizard',
            options={'verbose_name': '修改价格', 'verbose_name_plural': '修改价格'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': '订单', 'verbose_name_plural': '订单'},
        ),
        migrations.AlterModelOptions(
            name='ordergoods',
            options={'verbose_name': '订单商品', 'verbose_name_plural': '订单商品'},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'verbose_name': '支付记录', 'verbose_name_plural': '支付记录'},
        ),
        migrations.AlterModelOptions(
            name='shipper',
            options={'verbose_name': '承运商', 'verbose_name_plural': '承运商'},
        ),
        migrations.AlterModelOptions(
            name='wechatuser',
            options={'verbose_name': '微信用户', 'verbose_name_plural': '微信用户'},
        ),
        migrations.RemoveField(
            model_name='attachment',
            name='owner_type',
        ),
        migrations.RemoveField(
            model_name='goods',
            name='barCode',
        ),
        migrations.RemoveField(
            model_name='goods',
            name='commission',
        ),
        migrations.RemoveField(
            model_name='goods',
            name='commission_type',
        ),
        migrations.RemoveField(
            model_name='goods',
            name='recommendStatusStr',
        ),
        migrations.RemoveField(
            model_name='goods',
            name='statusStr',
        ),
        migrations.AddField(
            model_name='category',
            name='eng_name',
            field=models.CharField(default='', max_length=100, verbose_name='名称(英文)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='icon',
            name='name',
            field=models.CharField(default='', max_length=20, verbose_name='图标名称'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='attachment',
            name='display_pic',
            field=models.ImageField(upload_to=wx_league.models.filepath, verbose_name='附件图片'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='owner_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wx_league.goods', verbose_name='所属货物'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='numberFav',
            field=models.IntegerField(default=0, verbose_name='收藏人数'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='numberGoodReputation',
            field=models.IntegerField(default=0, verbose_name='好评数量'),
        ),
        migrations.AlterField(
            model_name='ordergoods',
            name='display_pic',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='wx_league.Icon', verbose_name='图片'),
        ),
    ]
