# Generated by Django 2.1 on 2018-08-15 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wx_league', '0026_auto_20180815_1441'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='logistics',
            options={'verbose_name': '物流信息', 'verbose_name_plural': '物流信息'},
        ),
        migrations.AddField(
            model_name='order',
            name='logistics_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='wx_league.Logistics', verbose_name='物流id'),
            preserve_default=False,
        ),
    ]
