# Generated by Django 2.1 on 2018-08-16 01:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wx_league', '0027_auto_20180815_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='isDefault',
            field=models.BooleanField(default=False, verbose_name='默认地址'),
        ),
        migrations.AlterField(
            model_name='order',
            name='logistics_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='wx_league.Logistics', verbose_name='物流id'),
        ),
    ]
