# Generated by Django 2.1 on 2018-08-27 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wx_league', '0028_auto_20180816_0143'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coach', models.IntegerField(verbose_name='教练id')),
                ('train_ground', models.IntegerField(verbose_name='训练场id')),
                ('length_time', models.FloatField(verbose_name='预约时间长度')),
                ('book_time_start', models.DateTimeField(verbose_name='预约开始时间')),
                ('book_time_end', models.DateTimeField(verbose_name='预约结束时间')),
                ('last_active_time', models.DateTimeField(auto_now=True, verbose_name='最近操作时间')),
            ],
        ),
    ]
