# Generated by Django 2.1 on 2018-08-27 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wx_league', '0029_book'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'verbose_name': '学员教练预约', 'verbose_name_plural': '学员教练预约'},
        ),
        migrations.AlterModelTable(
            name='book',
            table='Book',
        ),
    ]
