# Generated by Django 2.1 on 2018-08-27 15:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wx_league', '0030_auto_20180827_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='coach',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='教练id'),
        ),
        migrations.AlterField(
            model_name='book',
            name='train_ground',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wx_league.DriverSchool', verbose_name='训练场id'),
        ),
    ]
