# Generated by Django 2.1 on 2018-08-27 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wx_league', '0032_auto_20180827_2008'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='status',
            field=models.SmallIntegerField(default=1, verbose_name='预约状态'),
            preserve_default=False,
        ),
    ]
