# Generated by Django 2.1 on 2018-08-30 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wx_league', '0034_kanjia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bargain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('times', models.IntegerField(default=0, verbose_name='砍价次数')),
                ('price', models.FloatField(verbose_name='砍价当前价格')),
                ('minPrice', models.FloatField(verbose_name='砍价最低价格')),
                ('calculate_method', models.CharField(max_length=50, verbose_name='砍价计算模式')),
                ('expected_price', models.FloatField(verbose_name='期望砍价价格')),
                ('expected_times', models.FloatField(verbose_name='期望砍价次数')),
                ('goods_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wx_league.goods', verbose_name='货物')),
            ],
            options={
                'db_table': 'Bargain',
                'verbose_name': '砍价',
            },
        ),
        migrations.RemoveField(
            model_name='kanjia',
            name='goods_id',
        ),
        migrations.DeleteModel(
            name='Kanjia',
        ),
    ]
