# Generated by Django 2.1 on 2018-08-30 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wx_league', '0035_auto_20180830_1828'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goods',
            name='minPrice',
        ),
        migrations.RemoveField(
            model_name='goods',
            name='pingtuanPrice',
        ),
        migrations.RemoveField(
            model_name='goods',
            name='user_id',
        ),
    ]
