# Generated by Django 2.1 on 2018-08-30 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wx_league', '0036_auto_20180830_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.SmallIntegerField(choices=[(0, '支付已完成'), (1, '待用户支付'), (2, '支付已关闭'), (3, '退款')], default=1, verbose_name='状态'),
        ),
    ]
