# Generated by Django 2.1 on 2018-08-30 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wx_league', '0037_auto_20180830_1904'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoodsReputation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_reputation_str', models.TextField(verbose_name='商品评论')),
                ('goods_reputation_remark', models.TextField(verbose_name='评论备注')),
                ('dates_reputation', models.DateTimeField(auto_now_add=True, verbose_name='评论日期')),
                ('goods_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wx_league.goods', verbose_name='商品')),
            ],
            options={
                'db_table': 'GoodsReputation',
                'verbose_name': '商品评论',
                'verbose_name_plural': '商品评论',
            },
        ),
    ]
