# Generated by Django 2.1 on 2018-08-30 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wx_league', '0039_auto_20180830_2041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodsreputation',
            name='goods_reputation_str',
            field=models.SmallIntegerField(choices=[(0, '特别好评'), (1, '好评'), (2, '中评'), (3, '差评')], max_length=20, verbose_name='评价级别'),
        ),
    ]
