# Generated by Django 2.1 on 2018-08-31 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wx_league', '0040_auto_20180830_2344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodsreputation',
            name='goods_reputation_str',
            field=models.SmallIntegerField(max_length=20, verbose_name='评价级别'),
        ),
    ]
