# Generated by Django 2.1 on 2018-08-31 00:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wx_league', '0042_auto_20180831_0005'),
    ]

    operations = [
        migrations.CreateModel(
            name='BargainUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': '砍价用户记录',
                'verbose_name_plural': '砍价用户记录',
                'db_table': 'BargainUser',
            },
        ),
        migrations.AlterModelOptions(
            name='bargain',
            options={'verbose_name': '砍价', 'verbose_name_plural': '砍价'},
        ),
        migrations.AddField(
            model_name='bargainuser',
            name='bargain_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wx_league.Bargain', verbose_name='砍价活动'),
        ),
        migrations.AddField(
            model_name='bargainuser',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='砍价用户'),
        ),
    ]
