# Generated by Django 2.1 on 2018-08-31 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wx_league', '0043_auto_20180831_0029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bargain',
            name='calculate_method',
            field=models.SmallIntegerField(choices=[(0, 'line'), (1, 'log')], max_length=50, verbose_name='砍价计算模式'),
        ),
    ]
