# Generated by Django 2.1 on 2018-08-31 23:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wx_league', '0054_auto_20180831_2146'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserExam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_status', models.SmallIntegerField(choices=[(0, '考试未报名'), (1, '考试已报名'), (2, '考试已经停止预约'), (3, '考试已经结束')], verbose_name='考试状态')),
                ('exam_type', models.SmallIntegerField(choices=[(0, '科目一'), (1, '科目二'), (2, '科目三'), (3, '科目四')], verbose_name='考试类型')),
                ('exam_results', models.FloatField(verbose_name='考试成绩')),
                ('dateAdd', models.DateTimeField(auto_now_add=True, verbose_name='考试开始时间')),
                ('dateEnd', models.DateTimeField(auto_now=True, verbose_name='考试结束时间')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='考生')),
            ],
            options={
                'verbose_name_plural': '学生考试信息',
                'verbose_name': '学生考试信息',
                'db_table': 'UserExam',
            },
        ),
        migrations.AlterField(
            model_name='attachment',
            name='owner_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wx_league.Goods', verbose_name='所属货物'),
        ),
        migrations.AlterField(
            model_name='bargain',
            name='goods_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wx_league.Goods', verbose_name='货物'),
        ),
        migrations.AlterField(
            model_name='coupons',
            name='goods_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wx_league.Goods', verbose_name='商品id'),
        ),
        migrations.AlterField(
            model_name='goodsreputation',
            name='goods_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wx_league.Goods', verbose_name='商品'),
        ),
    ]
