# Generated by Django 2.1 on 2018-09-01 00:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wx_league', '0057_auto_20180901_0020'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoachDriverSchool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='教练id')),
                ('train_ground', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='wx_league.DriverSchool', verbose_name='训练场id')),
            ],
            options={
                'verbose_name_plural': '教练所属驾校',
                'db_table': 'CoachDriverSchool',
                'verbose_name': '教练所属驾校',
            },
        ),
        migrations.AddField(
            model_name='userexam',
            name='train_ground',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='wx_league.DriverSchool', verbose_name='训练场id'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='attachment',
            name='owner_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wx_league.Goods', verbose_name='所属货物'),
        ),
        migrations.AlterField(
            model_name='bargain',
            name='goods_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wx_league.Goods', verbose_name='货物'),
        ),
        migrations.AlterField(
            model_name='coupons',
            name='goods_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wx_league.Goods', verbose_name='商品id'),
        ),
        migrations.AlterField(
            model_name='goodsreputation',
            name='goods_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wx_league.Goods', verbose_name='商品'),
        ),
    ]
