# Generated by Django 2.1 on 2018-09-05 06:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wx_league', '0074_auto_20180902_1530'),
    ]

    operations = [
        migrations.CreateModel(
            name='Forum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='标题')),
                ('content', models.TextField(verbose_name='帖子内容')),
                ('repley_count', models.IntegerField(verbose_name='回复数量')),
                ('time_add', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('last_reply_time', models.DateTimeField(auto_now=True, verbose_name='最后回复时间')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='帖子发表者')),
            ],
            options={
                'db_table': 'Forum',
                'verbose_name': '帖子',
                'verbose_name_plural': '帖子',
            },
        ),
        migrations.CreateModel(
            name='ForumReply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='回复内容')),
                ('forum_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wx_league.Forum', verbose_name='论坛内容')),
                ('user_id', models.ForeignKey(default='用户已注销', on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL, verbose_name='回复用户')),
            ],
            options={
                'db_table': 'ForumReply',
                'verbose_name': '帖子回复',
                'verbose_name_plural': '帖子回复',
            },
        ),
        migrations.AlterField(
            model_name='attachment',
            name='owner_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wx_league.Goods', verbose_name='所属货物'),
        ),
        migrations.AlterField(
            model_name='bargain',
            name='goods_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wx_league.Goods', verbose_name='货物'),
        ),
        migrations.AlterField(
            model_name='coupons',
            name='goods_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wx_league.Goods', verbose_name='商品id'),
        ),
        migrations.AlterField(
            model_name='goodsreputation',
            name='goods_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wx_league.Goods', verbose_name='商品'),
        ),
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.CharField(blank=True, max_length=100, verbose_name='详细地址'),
        ),
        migrations.AlterField(
            model_name='order',
            name='linkman',
            field=models.CharField(blank=True, max_length=100, verbose_name='联系人'),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.CharField(blank=True, max_length=50, verbose_name='手机号码'),
        ),
        migrations.AlterField(
            model_name='order',
            name='postcode',
            field=models.CharField(blank=True, max_length=20, verbose_name='邮政编码'),
        ),
        migrations.AlterField(
            model_name='order',
            name='remark',
            field=models.CharField(blank=True, max_length=100, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='order',
            name='traces',
            field=models.TextField(blank=True, verbose_name='物流信息'),
        ),
    ]
