# Generated by Django 2.1 on 2018-09-05 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wx_league', '0075_auto_20180905_0637'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='主题名字')),
                ('description', models.CharField(max_length=255, verbose_name='主题介绍')),
                ('eng_name', models.CharField(max_length=100, verbose_name='名称(英文)')),
                ('level', models.SmallIntegerField(verbose_name='分类级别')),
                ('is_use', models.BooleanField(default=True, verbose_name='是否启用')),
                ('sort', models.IntegerField(verbose_name='排序')),
                ('icon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wx_league.Icon', verbose_name='图标')),
                ('pid', models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='wx_league.Category', verbose_name='上级主题')),
            ],
            options={
                'verbose_name': '主题',
                'verbose_name_plural': '主题',
                'db_table': 'Topic',
            },
        ),
        migrations.AlterField(
            model_name='attachment',
            name='owner_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wx_league.Goods', verbose_name='所属货物'),
        ),
        migrations.AlterField(
            model_name='bargain',
            name='goods_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wx_league.Goods', verbose_name='货物'),
        ),
        migrations.AlterField(
            model_name='coupons',
            name='goods_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wx_league.Goods', verbose_name='商品id'),
        ),
        migrations.AlterField(
            model_name='goodsreputation',
            name='goods_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wx_league.Goods', verbose_name='商品'),
        ),
        migrations.AddField(
            model_name='forum',
            name='Topic_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='wx_league.Topic', verbose_name='主题'),
            preserve_default=False,
        ),
    ]
