# Generated by Django 2.1 on 2018-09-08 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wx_league', '0077_auto_20180907_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='owner_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wx_league.Goods', verbose_name='所属货物'),
        ),
        migrations.AlterField(
            model_name='bargain',
            name='goods_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wx_league.Goods', verbose_name='货物'),
        ),
        migrations.AlterField(
            model_name='book',
            name='status',
            field=models.SmallIntegerField(default=0, verbose_name='预约状态'),
        ),
        migrations.AlterField(
            model_name='bookset',
            name='book_date_end',
            field=models.DateTimeField(null=True, verbose_name='预约设置结束的日期'),
        ),
        migrations.AlterField(
            model_name='bookset',
            name='book_date_start',
            field=models.DateTimeField(null=True, verbose_name='预约设置开始的日期'),
        ),
        migrations.AlterField(
            model_name='coupons',
            name='goods_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wx_league.Goods', verbose_name='商品id'),
        ),
        migrations.AlterField(
            model_name='goodsreputation',
            name='goods_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wx_league.Goods', verbose_name='商品'),
        ),
    ]
