# Generated by Django 2.1.1 on 2018-10-04 10:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wx_league', '0092_auto_20181003_2221'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrowseRecords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('browse_time', models.DateTimeField(auto_now_add=True, verbose_name='浏览时间')),
            ],
            options={
                'db_table': 'BrowseRecords',
                'verbose_name_plural': '浏览记录',
                'verbose_name': '浏览记录',
            },
        ),
        migrations.AddField(
            model_name='forum',
            name='browse_times',
            field=models.IntegerField(default=0, verbose_name='浏览次数'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='owner_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wx_league.Goods', verbose_name='所属货物'),
        ),
        migrations.AlterField(
            model_name='bargain',
            name='calculate_method',
            field=models.SmallIntegerField(choices=[(0, 'line'), (1, 'log')], verbose_name='砍价计算模式'),
        ),
        migrations.AlterField(
            model_name='bargain',
            name='goods_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wx_league.Goods', verbose_name='货物'),
        ),
        migrations.AlterField(
            model_name='coupons',
            name='goods_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wx_league.Goods', verbose_name='商品id'),
        ),
        migrations.AlterField(
            model_name='goodsreputation',
            name='goods_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wx_league.Goods', verbose_name='商品'),
        ),
        migrations.AddField(
            model_name='browserecords',
            name='forum_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='wx_league.Forum', verbose_name='浏览记录'),
        ),
        migrations.AddField(
            model_name='browserecords',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='访客'),
        ),
    ]
