# Generated by Django 2.1.2 on 2018-11-26 18:03

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wx_league', '0109_auto_20181126_1600'),
    ]

    operations = [
        migrations.AddField(
            model_name='wechatuser',
            name='username',
            field=models.CharField(blank=True, help_text='Required. 30 characters or fewer. Letters, digits and ./+/-/_ only.', max_length=30, validators=[django.core.validators.RegexValidator('^[\\w.+-]+$', 'Enter a valid username jebal.', 'invalid')], verbose_name='username'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='owner_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wx_league.Goods', verbose_name='所属货物'),
        ),
        migrations.AlterField(
            model_name='bargain',
            name='goods_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wx_league.Goods', verbose_name='货物'),
        ),
        migrations.AlterField(
            model_name='coupons',
            name='goods_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wx_league.Goods', verbose_name='商品id'),
        ),
        migrations.AlterField(
            model_name='goodsreputation',
            name='goods_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wx_league.Goods', verbose_name='商品'),
        ),
    ]
