# Generated by Django 2.1 on 2018-08-06 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wx_league', '0003_auto_20180806_0109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wechatuser',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
    ]
