# Generated by Django 2.1 on 2018-08-06 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wx_league', '0005_auto_20180806_0115'),
    ]

    operations = [
        migrations.CreateModel(
            name='address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province_id', models.SmallIntegerField(default=0, verbose_name='省')),
                ('city_id', models.SmallIntegerField(default=0, verbose_name='城市')),
                ('district_id', models.SmallIntegerField(default=0, verbose_name='区')),
                ('linkMan', models.CharField(max_length=15, verbose_name='联系人')),
                ('address', models.CharField(max_length=100, verbose_name='详细地址')),
                ('mobile', models.CharField(max_length=40, verbose_name='电话号码')),
                ('code', models.CharField(max_length=20, verbose_name='邮政编码')),
                ('isDefault', models.BooleanField(verbose_name='默认地址')),
                ('owner_type', models.SmallIntegerField(verbose_name='被标注地址的类型eg:微信用户,订单')),
                ('owner_id', models.IntegerField(verbose_name='微信用户、订单的id')),
            ],
        ),
    ]
