# Generated by Django 2.1 on 2018-08-06 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wx_league', '0006_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wechatuser',
            name='city',
            field=models.IntegerField(default=0, verbose_name='城市'),
        ),
        migrations.AlterField(
            model_name='wechatuser',
            name='country',
            field=models.IntegerField(default=0, verbose_name='国家'),
        ),
        migrations.AlterField(
            model_name='wechatuser',
            name='province',
            field=models.IntegerField(default=0, verbose_name='省份'),
        ),
    ]
