# Generated by Django 2.1 on 2018-08-10 02:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('wx_league', '0007_auto_20180810_0236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupons',
            name='date_add',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='优惠券添加的时间'),
        ),
    ]
