# Generated by Django 2.1 on 2018-08-07 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wx_league', '0007_auto_20180806_0412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='city_id',
            field=models.IntegerField(default=0, verbose_name='城市'),
        ),
        migrations.AlterField(
            model_name='address',
            name='district_id',
            field=models.IntegerField(default=0, verbose_name='区'),
        ),
        migrations.AlterField(
            model_name='address',
            name='province_id',
            field=models.IntegerField(default=0, verbose_name='省'),
        ),
    ]
