# Generated by Django 2.1 on 2018-08-07 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wx_league', '0008_auto_20180807_0029'),
    ]

    operations = [
        migrations.CreateModel(
            name='goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barCode', models.CharField(default='', max_length=100, verbose_name='条形码')),
                ('characteristic', models.CharField(default='', max_length=100, verbose_name='描述')),
                ('commission', models.FloatField(verbose_name='佣金')),
                ('commission_type', models.IntegerField(default=0, verbose_name='佣金类型')),
                ('dateAdd', models.DateTimeField(auto_now_add=True, verbose_name='上架时间')),
                ('dateStart', models.DateTimeField(auto_now_add=True, verbose_name='上架时间')),
                ('dateUpdate', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('logistics_id', models.IntegerField(default=0, verbose_name='物流id')),
                ('MinPrice', models.FloatField(verbose_name='最小价格')),
                ('MinScore', models.SmallIntegerField(default=0, verbose_name='最小评分')),
                ('name', models.CharField(max_length=60, verbose_name='名称')),
                ('numberFav', models.IntegerField(default=0)),
                ('numberGoodReputation', models.IntegerField(default=0)),
                ('numberOrders', models.IntegerField(default=0)),
                ('originalPrice', models.FloatField(verbose_name='原价')),
                ('paixu', models.IntegerField(default=0)),
                ('pic', models.TextField(verbose_name='商品图片连接')),
                ('pingtuan', models.BooleanField(default=False, verbose_name='拼团')),
                ('pingtuanPrice', models.FloatField(default=0.0, verbose_name='拼团价格')),
                ('recommendStatus', models.SmallIntegerField(default=0, verbose_name='推荐状态')),
                ('status', models.SmallIntegerField(default=0, verbose_name='商品状态')),
                ('stores', models.IntegerField(verbose_name='库存')),
                ('user_id', models.IntegerField(default=0)),
                ('video_id', models.IntegerField(default=0)),
                ('views', models.IntegerField(default=0)),
                ('weight', models.FloatField(default=0.0)),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wx_league.Category')),
                ('shop_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wx_league.DriverSchool', verbose_name='商店id')),
            ],
        ),
    ]
