# Generated by Django 2.1 on 2018-08-07 09:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wx_league', '0009_goods'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='pid',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='wx_league.Category', verbose_name='上级分类'),
        ),
        migrations.AlterField(
            model_name='driverschool',
            name='pic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='wx_league.Attachment', verbose_name='图片'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='category_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='wx_league.Category'),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipper_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='wx_league.Shipper', verbose_name='快递承运商'),
        ),
        migrations.AlterField(
            model_name='order',
            name='wechat_user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='微信用户'),
        ),
        migrations.AlterField(
            model_name='ordergoods',
            name='pic',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='wx_league.Attachment', verbose_name='图片'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='wechat_user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='微信用户'),
        ),
    ]
