# Generated by Django 2.1 on 2018-08-07 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wx_league', '0010_auto_20180807_0918'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='pid',
        ),
    ]
