# Generated by Django 2.1 on 2018-08-11 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wx_league', '0011_auto_20180811_2348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupons_users',
            name='coupons_id',
            field=models.IntegerField(verbose_name='优惠券id'),
        ),
    ]
