# Generated by Django 2.1 on 2018-08-07 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wx_league', '0012_category_pid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='pic',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='wx_league.Attachment', verbose_name='商品图片连接'),
        ),
    ]
