# Generated by Django 2.1 on 2018-08-09 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wx_league', '0014_auto_20180807_0936'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goods',
            old_name='MinPrice',
            new_name='minPrice',
        ),
        migrations.RenameField(
            model_name='goods',
            old_name='MinScore',
            new_name='minScore',
        ),
        migrations.AlterField(
            model_name='goods',
            name='numberOrders',
            field=models.IntegerField(default=0, verbose_name='已售数量'),
        ),
    ]
