# Generated by Django 2.1 on 2018-08-09 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wx_league', '0015_auto_20180809_0647'),
    ]

    operations = [
        migrations.CreateModel(
            name='Icon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_pic', models.ImageField(upload_to='img', verbose_name='icon 对应')),
            ],
            options={
                'db_table': 'Icon',
            },
        ),
        migrations.AddField(
            model_name='attachment',
            name='owner_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='attachment',
            name='owner_type',
            field=models.CharField(choices=[('DriverSchool', 'DriverSchool'), ('WechatUser', 'WechatUser'), ('Goods', 'Goods'), ('Unkown', 'Unkown')], default='Unkown', max_length=20),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='display_pic',
            field=models.ImageField(upload_to='img', verbose_name='附件图片'),
        ),
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wx_league.Icon', verbose_name='图标'),
        ),
        migrations.AlterField(
            model_name='driverschool',
            name='pic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='wx_league.Icon', verbose_name='驾校商标'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='pic',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='wx_league.Icon', verbose_name='商品图片连接'),
        ),
        migrations.AlterField(
            model_name='ordergoods',
            name='pic',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='wx_league.Icon', verbose_name='图片'),
        ),
    ]
