# Generated by Django 2.1 on 2018-08-09 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wx_league', '0016_auto_20180809_0733'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='优惠券名称')),
                ('moneyMin', models.FloatField(verbose_name='优惠券金额')),
                ('moneyHreshold', models.FloatField(verbose_name='满 减 最低额度')),
                ('dateEndType', models.SmallIntegerField(choices=[(0, '截止某日前有效'), (1, '领取后有效时间倒计')], verbose_name='优惠券有效期类型')),
                ('dateEndDays', models.DateTimeField(verbose_name='优惠券截止时间')),
                ('date', models.SmallIntegerField(verbose_name='优惠券有效期倒计时(天)')),
                ('goods_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wx_league.goods', verbose_name='商品id')),
            ],
        ),
    ]
