# Generated by Django 2.1 on 2018-08-12 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wx_league', '0018_auto_20180812_0631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='number_goods',
            field=models.IntegerField(default=0, verbose_name='商品数量'),
        ),
    ]
