# Generated by Django 2.1 on 2018-08-12 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wx_league', '0023_remove_ordergoods_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='icon',
            name='display_pic',
            field=models.ImageField(upload_to='img/1345341503480400054', verbose_name='icon 对应'),
        ),
    ]
