# Generated by Django 2.1 on 2018-08-14 05:21

from django.db import migrations, models
import wx_league.models


class Migration(migrations.Migration):

    dependencies = [
        ('wx_league', '0025_auto_20180812_0856'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': '商品分类', 'verbose_name_plural': '商品分类'},
        ),
        migrations.AlterModelOptions(
            name='coupons',
            options={'verbose_name': '优惠券', 'verbose_name_plural': '优惠券'},
        ),
        migrations.AlterModelOptions(
            name='coupons_users',
            options={'verbose_name': '用户领取的优惠券', 'verbose_name_plural': '用户领取的优惠券'},
        ),
        migrations.AlterModelOptions(
            name='goods',
            options={'verbose_name': '商品', 'verbose_name_plural': '商品'},
        ),
        migrations.AlterModelOptions(
            name='icon',
            options={'verbose_name': '图标', 'verbose_name_plural': '图标'},
        ),
        migrations.AlterModelOptions(
            name='modifypricewizard',
            options={'verbose_name': '修改价格', 'verbose_name_plural': '修改价格'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': '订单', 'verbose_name_plural': '订单'},
        ),
        migrations.AlterModelOptions(
            name='ordergoods',
            options={'verbose_name': '订单商品', 'verbose_name_plural': '订单商品'},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'verbose_name': '支付记录', 'verbose_name_plural': '支付记录'},
        ),
        migrations.AlterModelOptions(
            name='shipper',
            options={'verbose_name': '承运商', 'verbose_name_plural': '承运商'},
        ),
        migrations.AlterModelOptions(
            name='wechatuser',
            options={'verbose_name': '微信用户', 'verbose_name_plural': '微信用户'},
        ),
        migrations.AddField(
            model_name='icon',
            name='name',
            field=models.CharField(default='', max_length=20, verbose_name='图标名称'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='attachment',
            name='display_pic',
            field=models.ImageField(upload_to=wx_league.models.filepath, verbose_name='附件图片'),
        ),
        migrations.AlterModelTable(
            name='coupons',
            table='Coupons',
        ),
        migrations.AlterModelTable(
            name='coupons_users',
            table='Coupons_users',
        ),
    ]
