# Generated by Django 2.1 on 2018-08-14 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wx_league', '0026_auto_20180814_0521'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='driverschool',
            options={'verbose_name': '驾校', 'verbose_name_plural': '驾校'},
        ),
    ]
