# Generated by Django 2.1 on 2018-08-14 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wx_league', '0027_auto_20180814_0524'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='eng_name',
            field=models.CharField(default='', max_length=100, verbose_name='名称(英文)'),
            preserve_default=False,
        ),
    ]
