# Generated by Django 2.1 on 2018-08-14 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wx_league', '0028_category_eng_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attachment',
            options={'verbose_name': '图标', 'verbose_name_plural': '图标'},
        ),
        migrations.RemoveField(
            model_name='attachment',
            name='owner_type',
        ),
        migrations.AlterField(
            model_name='attachment',
            name='owner_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wx_league.goods', verbose_name='所属货物'),
        ),
    ]
