# Generated by Django 2.1 on 2018-08-14 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wx_league', '0029_auto_20180814_1100'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attachment',
            options={'verbose_name': '图片', 'verbose_name_plural': '图片'},
        ),
        migrations.RemoveField(
            model_name='goods',
            name='barCode',
        ),
        migrations.RemoveField(
            model_name='goods',
            name='commission',
        ),
        migrations.RemoveField(
            model_name='goods',
            name='commission_type',
        ),
        migrations.RemoveField(
            model_name='goods',
            name='recommendStatusStr',
        ),
        migrations.RemoveField(
            model_name='goods',
            name='statusStr',
        ),
        migrations.AlterField(
            model_name='goods',
            name='numberFav',
            field=models.IntegerField(default=0, verbose_name='收藏人数'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='numberGoodReputation',
            field=models.IntegerField(default=0, verbose_name='好评数量'),
        ),
    ]
